import React, { useState } from 'react';
import axios from 'axios';

const EWayBillConsigner=()=> {
  const [docType, setDocType] = useState('INV');
  const [docNo, setDocNo] = useState('Perione-2');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);

  const handleSearch = async (e) => {
    e.preventDefault();
    setLoading(true);
    setResponse(null);

    try {
      const res = await axios.get('http://localhost:5000/api/ewaybill/by-consigner', {
        params: { docType, docNo },
      });
      setResponse({ success: true, data: res.data });
    } catch (err) {
      setResponse({
        success: false,
        data: err.response?.data || { message: err.message },
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={cardStyle}>
      <h3>5. Get E-Way Bill Generated by Consigner</h3>
      <form onSubmit={handleSearch} style={formStyle}>
        <div>
          <label>Document Type:</label>
          <input
            type="text"
            value={docType}
            onChange={(e) => setDocType(e.target.value)}
            placeholder="INV / CHL / BOL"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label>Document Number:</label>
          <input
            type="text"
            value={docNo}
            onChange={(e) => setDocNo(e.target.value)}
            placeholder="e.g. Perione-2"
            required
            style={inputStyle}
          />
        </div>
        <button type="submit" disabled={loading} style={buttonStyle}>
          {loading ? 'Searching...' : 'Search E-Way Bill'}
        </button>
      </form>
      <ResponseViewer response={response} />
    </div>
  );
}
export default EWayBillConsigner;